apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
  namespace: "nginx-app"
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
    env: {{ .Values.pod.labelEnv }}
spec:
  type: {{ .Values.service.type }}  # Exposes the service externally
  selector:
    app: {{ .Values.pod.labelApp }}
    #env: {{ .Values.pod.labelEnv }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}        # Service port that clients connect to
      targetPort: {{ .Values.service.port }}  # Forward traffic to container's port
      nodePort: {{ .Values.service.nodePort }}   